based_on_package: "sbot_ro1_mock"

hardware:
  robot_description:
    urdf:
      package: "sbot_ro1_sim"
      path: "description/sbot_ro1_sim.urdf.xacro"
    urdf_params:
      - use_fake_hardware: "false"
      - mujoco_model: "description/mujoco/scene.xml"
      - mujoco_viewer: false

objectives:
  behavior_loader_plugins:
    core:
      - "moveit_pro::behaviors::CoreBehaviorsLoader"
      - "moveit_pro::behaviors::MTCCoreBehaviorsLoader"
      - "moveit_pro::behaviors::VisionBehaviorsLoader"
      - "moveit_pro::behaviors::ConverterBehaviorsLoader"
      - "moveit_pro::behaviors::MujocoBehaviorsLoader"
  objective_library_paths:
    core_objectives:
      package_name: "moveit_pro_objectives"
      relative_path: "objectives/core"
    motion_objectives:
      package_name: "moveit_pro_objectives"
      relative_path: "objectives/motion"
    perception_objectives:
      package_name: "moveit_pro_objectives"
      relative_path: "objectives/perception"
    mujoco_objectives:
      package_name: "moveit_pro_objectives"
      relative_path: "objectives/mujoco"
    sbot_ro1_objectives:
      package_name: "sbot_ro1_mock"
      relative_path: "objectives"
    sbot_ro1_sim_objectives:
      package_name: "sbot_ro1_sim"
      relative_path: "objectives"
  waypoints_file:
    package_name: "sbot_ro1_sim"
    relative_path: "waypoints/waypoints.yaml"
