<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>sbot_ro1_mock</name>
  <version>0.0.1</version>
  <description>MoveIt Pro mock configuration for the Standard Bots RO1 6-DOF arm.</description>
  <maintainer email="sanchit.badamikar@picknik.ai">Sanchit Badamikar</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>standard_bots_description</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
