hardware:
  simulated: true
  launch_control_node: true
  launch_robot_state_publisher: true
  robot_description:
    urdf:
      package: "sbot_core_base_config"
      path: "description/sbot_core.urdf.xacro"
    srdf:
      package: "sbot_core_base_config"
      path: "config/moveit/sbot_core.srdf"
    urdf_params:
      - use_fake_hardware: "true"

moveit_params:
  joint_group_name: "manipulator"
  kinematics:
    package: "sbot_core_base_config"
    path: "config/moveit/kinematics.yaml"
  sensors_3d:
    package: "sbot_core_base_config"
    path: "config/moveit/sensors_3d.yaml"
  joint_limits:
    package: "sbot_core_base_config"
    path: "config/moveit/joint_limits.yaml"
  pose_jog:
    package: "sbot_core_base_config"
    path: "config/moveit/pose_jog.yaml"
  joint_jog:
    package: "sbot_core_base_config"
    path: "config/moveit/joint_jog.yaml"
  publish:
    planning_scene: true
    geometry_updates: true
    state_updates: true
    transforms_updates: true
  trajectory_execution:
    manage_controllers: true
    allowed_execution_duration_scaling: 2.0
    allowed_goal_duration_margin: 5.0
    allowed_start_tolerance: 0.01

ros2_control:
  config:
    package: "sbot_core_base_config"
    path: "config/control/sbot_core_ros2_control.yaml"
  controllers_active_at_startup:
    - "joint_state_broadcaster"
    - "joint_trajectory_admittance_controller"
  controllers_inactive_at_startup:
    - "joint_velocity_controller"
    - "velocity_force_controller"

objectives:
  behavior_loader_plugins:
    core:
      - "moveit_pro::behaviors::CoreBehaviorsLoader"
      - "moveit_pro::behaviors::MTCCoreBehaviorsLoader"
      - "moveit_pro::behaviors::VisionBehaviorsLoader"
      - "moveit_pro::behaviors::ConverterBehaviorsLoader"
  objective_library_paths:
    core_objectives:
      package_name: "moveit_pro_objectives"
      relative_path: "objectives/core"
    motion_objectives:
      package_name: "moveit_pro_objectives"
      relative_path: "objectives/motion"
    perception_objectives:
      package_name: "moveit_pro_objectives"
      relative_path: "objectives/perception"
    sbot_core_objectives:
      package_name: "sbot_core_base_config"
      relative_path: "objectives"
  waypoints_file:
    package_name: "sbot_core_base_config"
    relative_path: "waypoints/waypoints.yaml"
